ThomasParratt/ft_irc

- Makefile
- src/Server.cpp
- src/Server.hpp
- src/main.cpp
added Server.hpp and Server.cpp
> 2811 jlu pollattempts

- Makefile
- src/Client.cpp
- src/Msg.hpp
- src/Server.cpp
- src/Server.hpp
- src/createMsgs.cpp
Feat: Added a Msg Creator and Command Selector and Copy Pasted two commands.
1 Msg Creator (createMsg function) creates Msg objects containing the msg received from Irssi.
-> Msg.command
-> Msg.parameters
-> Msg.trailing_message
2. commandSelector will read Msg object and redirect to correct command function (f.ex. PASS -> passwordCommand().
3. Copy Pasted two commands:
- Password
-Nickname
> 0412 mkorpela create msgs

- src/Server.cpp
- src/Server.hpp
- src/createMsgs.cpp
Client disconnects when the password is wrong.
> password check working

- src/Client.cpp
- src/Client.hpp
- src/Server.cpp
- src/Server.hpp
- src/createMsgs.cpp
- src/main.cpp
added:
signal handling
global variable for the server.loop
leave/join channel functions with private variable for server.hpp and client.hpp
> 6 12 jlu signal handle

- Makefile
- src/Channel.cpp
- src/Channel.hpp
- src/Client.hpp
- src/Server.hpp
- src/createMsgs.cpp
Added:
1. Channel object
2. join function (early version)
> Added Channel Object and Started Join channel

- Makefile
- src/Server.cpp
- src/Server.hpp
- src/createMsgs.cpp
- src/privmsg.cpp
Added Feature:  privmsgCommmand
1. Allows for group chat
2. Allows for DMs
> 1212 mkorpela privmsg command

- Makefile
- src/Server.cpp
- src/Server.hpp
- src/connectionMessages.cpp
- src/createMsgs.cpp
- src/kick.cpp
Kick
- a channel user can kick another channel user from the channel if it has operator permissions. The kicked user is then removed as a user of that channel.
> 1112 tparratt kick invite

- src/Client.cpp
- src/Client.hpp
- src/Server.hpp
- src/connectionMessages.cpp
- src/createMsgs.cpp
- src/kick.cpp
- The server will now not allow multiple clients with the same nickname to connect. It automatically changes their names so they are different.
- Added hostIP attribute to Client class. This contains a string representation of the client ip address which is needed in message 001.
- Username is also being set in message 001.
> 1312 tparratt nick user

- src/Client.cpp
- src/Client.hpp
- src/Server.cpp
- src/connectionMessages.cpp
- src/createMsgs.cpp
- src/join.cpp
- src/kick.cpp
- src/mode.cpp
- src/privmsg.cpp
- Now parses messages from netcat. Previously it didn't because netcat doesn't send carriage return.
- A user only join an invite only channel if the user has been invited.
- A user is now unable to send messages to a channel of which it is not a member (for example, after parting)
- Must have a password to connect
> 1912 tparratt issues

- Makefile
- src/Server.hpp
- src/handleUserInput.cpp
- src/main.cpp
And yes, there is a try-catch for our stoi. :)
> Added User input checks into main

- src/Server.cpp
- A message received from the client is only handled once the whole command has been received.
> 2012 tparratt

- Makefile
- src/Channel.cpp
- src/Channel.hpp
- src/Client.hpp
- src/Server.cpp
- src/Server.hpp
- src/channelUtils.cpp
- src/initializeMsg.cpp
- src/join.cpp
- src/joinChecks.cpp
- src/kick.cpp
- src/makeMessages.cpp
- src/makeSelectAndRunCommand.cpp
- src/privmsg.cpp
> 0701 mkorpela refactoring channelfunctions

- src/Server.cpp
Fixed segfault we had when a wrong password was entered
> 0801 tparratt pass seg fault

- src/Channel.hpp
- src/connectionMessages.cpp
When a client nickname is changed the nickname of the channel user is also updated.
> 0801 tparratt nick fix

- src/Server.cpp
- src/Server.hpp
- src/kick.cpp
A user is now removed from all channels of which it is a member when it disconnects from the server.
> 0901 tparratt client disconnection

- src/invite.cpp
- src/kick.cpp
Kick and Invite work as they should.
Code tidied up and comments removed.
> 1001 tparratt kick invite

- src/Server.cpp
- src/Server.hpp
- src/channelUtils.cpp
- src/join.cpp
- src/kick.cpp
- src/mode.cpp
- src/part.cpp
- src/topic.cpp
- kick segfault fixed
- server no longer stops when a client quits
> 1301 tparratt 

- src/Server.cpp
- src/Server.hpp
- src/channelUtils.cpp
- src/join.cpp
- src/makeSelectAndRunCommand.cpp
- src/mode.cpp
Fixed
-mode +k -> segfault
-mode +l -> segfault
-mode +l2 (concatenation)
Refactored with functions for each type of mode (f.ex. +i/  +l).
> Mode fixes and refactoring

- src/Channel.hpp
- src/Client.hpp
- src/Msg.hpp
- src/Server.cpp
- src/Server.hpp
- src/channelUtils.cpp
- src/connectionMessages.cpp
- src/invite.cpp
- src/join.cpp
- src/kick.cpp
- src/mode.cpp
- src/part.cpp
- src/privmsg.cpp
- src/topic.cpp
- Underscore added to private attributes that were missing an underscore at the beginning
- Removed all unnecessary includes in .hpp files
> 1401 tparratt tidy

- src/Channel.cpp
- src/Channel.hpp
- src/Server.cpp
- src/channelUtils.cpp
- src/invite.cpp
- src/joinChecks.cpp
- src/kick.cpp
- src/mode.cpp
- src/part.cpp
- src/topic.cpp
1. Changed all Channel attributes from public to private
2. Also added and created methods into code for the above transition.
> 1401 mkorpela channel attibutes to private

- Makefile
- src/Server.cpp
- src/connectionMessages.cpp
- src/join.cpp
- src/joinChecks.cpp
- src/mode.cpp
- src/part.cpp
updated doesChannelHavePassword() with just the bool check so we don't have to worry about edge case
join Message 353 fixed, took away the priv msg for number of ops and etc.
included message 366 in joinMessage so the channel info is complete.
added bool var to make sure that join message isn't sent twice
Quit works properly informing everyone in the channel
nickName changed now broadcast in each channel that the client nick changed
> 	updated mode -k to setChannelKey()

- Makefile
- src/Server.cpp
- src/Server.hpp
- src/connectionMessages.cpp
- src/invite.cpp
- src/join.cpp
- src/joinChecks.cpp
- src/kick.cpp
- src/makeSelectAndRunCommand.cpp
- src/mode.cpp
- src/part.cpp
- src/privmsg.cpp
- src/topic.cpp
1. Took away clientsocket as a function parameter in many functions
2. Also got rid of int return in functions that weren't passing a meaningful int
3. Clean up
> Reducing function parameters

- src/Server.hpp
- src/join.cpp
- Issue #72 fixed
- Tidied up join.cpp
> fixed issue #72 and refactored code

- src/clientLoop.cpp
- src/makeMessages.cpp
- Can send messages to the server from netcat.
- Also works if the message is sent in parts using ctrl + D.
> 2001 tparratt netcat

- src/serverLoop.cpp
> fixed valgrind error

- src/Server.hpp
- src/clientLoop.cpp
- src/handleUserInput.cpp
- src/serverInit.cpp
- src/serverLoop.cpp
Server and client sockets set to non-blocking
> 2101 tparratt nonblock
